package interfaces;

import BANCODEDADOS.ConexaoDAO;
import java.awt.Image;
import javax.swing.*;
import java.io.FileInputStream;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Adriano
 */
public class Registration extends javax.swing.JFrame {

    private FileInputStream fis;

    private int tamanho;

    /**
     * Creates new form Registration
     */
    Connection conn = null;
    PreparedStatement pst = null;

    public Registration() {
        setResizable(false);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Dia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CPF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Senha = new javax.swing.JPasswordField();
        Cadastrar = new javax.swing.JButton();
        Limpar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tipoConta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Mes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Ano = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        carregarFoto = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 227, 255));

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 0, 48)); // NOI18N
        jLabel1.setText("Crie uma conta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(jLabel1)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel2.setText("Nome completo:");

        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nascimento:");

        Dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiaActionPerformed(evt);
            }
        });

        jLabel4.setText("CPF:");

        CPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CPFActionPerformed(evt);
            }
        });

        jLabel5.setText("Email:");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        jLabel6.setText("Senha:");

        Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SenhaActionPerformed(evt);
            }
        });

        Cadastrar.setText("Cadastrar");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });

        Limpar.setText("Limpar");
        Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparActionPerformed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arara.png"))); // NOI18N

        tipoConta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Funcionário", "Administrador" }));
        tipoConta.setToolTipText("");
        tipoConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoContaActionPerformed(evt);
            }
        });

        jLabel9.setText("/");

        Mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MesActionPerformed(evt);
            }
        });

        jLabel10.setText("/");

        Ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoActionPerformed(evt);
            }
        });

        jLabel11.setText("Tipo de Conta:");

        carregarFoto.setText("Enviar Foto de Perfil");
        carregarFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carregarFotoActionPerformed(evt);
            }
        });

        lblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto.setText("FOTO (OPCIONAL)");
        lblFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(CPF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Nome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Email, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Senha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Ano, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197)
                        .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carregarFoto))
                        .addGap(126, 126, 126))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(Mes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addComponent(Ano))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(CPF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(carregarFoto)
                        .addGap(6, 6, 6)))
                .addGap(31, 31, 31)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addGap(3, 3, 3)
                        .addComponent(tipoConta, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(180, 180, 180))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void DiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiaActionPerformed
        String diaText = Dia.getText();

        // Verifica se o campo de dia contém apenas números e tem no máximo 2 dígitos
        if (!diaText.matches("\\d{1,2}")) {
            JOptionPane.showMessageDialog(null, "Valor inválido para o dia. Insira um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            Dia.setText(""); // Limpa o campo Campo_Dia
        }
    }//GEN-LAST:event_DiaActionPerformed

    private void CPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CPFActionPerformed
        //Validar CPF
        String cpf = CPF.getText();

        // Remover caracteres não numéricos do CPF
        cpf = cpf.replaceAll("[^0-9]", "");

        // Verificar se o CPF tem 11 dígitos
        if (cpf.length() != 11) {
            // CPF inválido
            JOptionPane.showMessageDialog(null, "CPF inválido. Por favor, insira um CPF válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Verificar se todos os dígitos são iguais
        boolean digitosIguais = true;
        for (int i = 1; i < 11; i++) {
            if (cpf.charAt(i) != cpf.charAt(0)) {
                digitosIguais = false;
                break;
            }
        }
        if (digitosIguais) {
            // CPF inválido
            JOptionPane.showMessageDialog(null, "CPF inválido. Por favor, insira um CPF válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calcular o primeiro dígito verificador
        int soma = 0;
        for (int i = 0; i < 9; i++) {
            soma += (cpf.charAt(i) - '0') * (10 - i);
        }
        int digito1 = 11 - (soma % 11);
        if (digito1 > 9) {
            digito1 = 0;
        }

        // Calcular o segundo dígito verificador
        soma = 0;
        for (int i = 0; i < 10; i++) {
            soma += (cpf.charAt(i) - '0') * (11 - i);
        }
        int digito2 = 11 - (soma % 11);
        if (digito2 > 9) {
            digito2 = 0;
        }

        // Verificar se os dígitos verificadores estão corretos
        if (digito1 == (cpf.charAt(9) - '0') && digito2 == (cpf.charAt(10) - '0')) {
            // CPF válido
            // Faça o que precisa ser feito
        } else {
            // CPF inválido
            JOptionPane.showMessageDialog(null, "CPF inválido. Por favor, insira um CPF válido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CPFActionPerformed

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        String email = Email.getText();
        String regex = "^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(email);
        boolean isEmailValid = matcher.matches();

        if (!isEmailValid) {
            JOptionPane.showMessageDialog(null, "O e-mail fornecido é inválido.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EmailActionPerformed

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed

        String nome = Nome.getText();
        String diaText = Dia.getText();
        String mesText = Mes.getText();
        String anoText = Ano.getText();
        String cpf = CPF.getText();
        String email = Email.getText();
        String senha = new String(Senha.getPassword());
        String tipoSelecionado = (String) tipoConta.getSelectedItem();

        // Verificar se todos os campos obrigatórios foram preenchidos
        if (nome.isEmpty() || diaText.isEmpty() || mesText.isEmpty() || anoText.isEmpty()
                || cpf.isEmpty() || email.isEmpty() || senha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos obrigatórios.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validar data de nascimento
        if (!diaText.matches("\\d{1,2}") || !mesText.matches("\\d{1,2}") || !anoText.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Data de nascimento inválida. Insira uma data válida.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int dia = Integer.parseInt(diaText);
        int mes = Integer.parseInt(mesText);
        int ano = Integer.parseInt(anoText);

        Calendar dataNascimento = Calendar.getInstance();
        dataNascimento.setLenient(false);
        dataNascimento.set(ano, mes - 1, dia); // Mês começa em zero no Calendar

        try {
            dataNascimento.getTime(); // Verificar se a data é válida

            // Calcular idade
            Calendar dataAtual = Calendar.getInstance();
            int idade = dataAtual.get(Calendar.YEAR) - dataNascimento.get(Calendar.YEAR);
            if (dataAtual.get(Calendar.MONTH) < dataNascimento.get(Calendar.MONTH)
                    || (dataAtual.get(Calendar.MONTH) == dataNascimento.get(Calendar.MONTH)
                    && dataAtual.get(Calendar.DAY_OF_MONTH) < dataNascimento.get(Calendar.DAY_OF_MONTH))) {
                idade--; // Ainda não fez aniversário no ano corrente
            }

            Connection conn = ConexaoDAO.conectaBD();

            // Inserir dados na tabela usuarios
            String sqlUsuarios = "INSERT INTO usuarios (nome_completo, data_nascimento, cpf, email, senha, tipo_conta, idade) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmUsuarios = conn.prepareStatement(sqlUsuarios);
            pstmUsuarios.setString(1, nome);
            pstmUsuarios.setDate(2, new java.sql.Date(dataNascimento.getTimeInMillis()));
            pstmUsuarios.setString(3, cpf);
            pstmUsuarios.setString(4, email);
            pstmUsuarios.setString(5, senha);
            pstmUsuarios.setString(6, tipoSelecionado);
            pstmUsuarios.setInt(7, idade);
            pstmUsuarios.executeUpdate();

            // Inserir dados na tabela autenticadoruser
            String sqlAutenticadorUser = "INSERT INTO autenticadoruser (email_user, senha_user) VALUES (?, ?)";
            PreparedStatement pstmAutenticadorUser = conn.prepareStatement(sqlAutenticadorUser);
            pstmAutenticadorUser.setString(1, email);
            pstmAutenticadorUser.setString(2, senha);
            pstmAutenticadorUser.executeUpdate();

            JOptionPane.showMessageDialog(null, "Inserido corretamente");

            // Abrir a tela de Login
            Loginn telaLogin = new Loginn();
            telaLogin.setVisible(true);

            // Fechar a tela de cadastro
            dispose();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao realizar o cadastro: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparActionPerformed
        //Limpar os campos de texto
        Nome.setText("");
        Dia.setText("");
        Mes.setText("");
        Ano.setText("");
        CPF.setText("");
        Email.setText("");
        Senha.setText("");
    }//GEN-LAST:event_LimparActionPerformed

    private void MesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MesActionPerformed
        String mesText = Mes.getText();

        // Verifica se o campo de mês contém apenas números e tem no máximo 2 dígitos
        if (!mesText.matches("\\d{1,2}")) {
            JOptionPane.showMessageDialog(null, "Valor inválido para o mês. Insira um número válido.", "Erro", JOptionPane.ERROR_MESSAGE);
            Mes.setText(""); // Limpa o campo Campo_Mes
        }
    }//GEN-LAST:event_MesActionPerformed

    private void SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SenhaActionPerformed
        String senha = Senha.getText();

        // Verifica se a senha está vazia
        if (senha.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo de senha vazio. Por favor, insira uma senha.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SenhaActionPerformed

    private void AnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoActionPerformed
        // Obtém o ano informado no campo Campo_Ano
        int ano = Integer.parseInt(Ano.getText());

        // Obtém a data atual
        Calendar dataAtual = Calendar.getInstance();

        // Define o limite de idade permitido
        Calendar limiteIdade = Calendar.getInstance();
        limiteIdade.add(Calendar.YEAR, -120);

        // Verifica se a diferença entre o ano informado e a data atual é maior que 120 anos
        if (dataAtual.get(Calendar.YEAR) - ano > 120) {
            JOptionPane.showMessageDialog(null, "Idade inválida. A idade não pode ser superior a 120 anos.", "Erro", JOptionPane.ERROR_MESSAGE);
            Ano.setText(""); // Limpa o campo Campo_Ano
        }

    }//GEN-LAST:event_AnoActionPerformed

    private void carregarFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carregarFotoActionPerformed

        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Selecionar arquivo");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Imagens", "jpg", "jpeg", "png");
        jfc.setFileFilter(filter);

        int result = jfc.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                fis = new FileInputStream(jfc.getSelectedFile());
                tamanho = (int) jfc.getSelectedFile().length();
                Image lblfoto = ImageIO.read(jfc.getSelectedFile()).getScaledInstance(lblFoto.getWidth(), lblFoto.getHeight(), Image.SCALE_SMOOTH);
                lblFoto.setIcon(new ImageIcon(lblfoto));
                lblFoto.updateUI();

            } catch (IOException e) {
                System.out.println(e);
            }

        }
    }//GEN-LAST:event_carregarFotoActionPerformed

    private void tipoContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoContaActionPerformed
        JComboBox comboBox = (JComboBox) evt.getSource();
        String selectedItem = (String) comboBox.getSelectedItem();

        if (selectedItem.equals("Funcionário")) {
            String fraseMagica = JOptionPane.showInputDialog("Insira a frase mágica para funcionário:");

            if (fraseMagica == null) {
                comboBox.setSelectedItem("Usuário"); // Volta para a opção "Usuário"
                return;
            }

            if (fraseMagica.equals("junindograu")) {
                // Ações para funcionário
                JOptionPane.showMessageDialog(null, "Bem-vindo, funcionário!");
                // Execute as ações apropriadas para funcionário
            } else {
                // Exiba mensagem de erro
                JOptionPane.showMessageDialog(null, "Frase mágica inválida para funcionário", "Erro", JOptionPane.ERROR_MESSAGE);
                comboBox.setSelectedItem("Usuário"); // Volta para a opção "Usuário"
            }
        } else if (selectedItem.equals("Usuário")) {
            // Ações para usuário
            JOptionPane.showMessageDialog(null, "Olá, usuário!");
            // Execute as ações apropriadas para usuário
        } else if (selectedItem.equals("Administrador")) {
            String fraseMagica = JOptionPane.showInputDialog("Insira a frase mágica para abrir função administrador:");

            if (fraseMagica == null) {
                comboBox.setSelectedItem("Usuário"); // Volta para a opção "Usuário"
                return;
            }

            if (fraseMagica.equals("admin123")) {
                // Ações para administrador
                JOptionPane.showMessageDialog(null, "Bem-vindo, administrador!");
                // Execute as ações apropriadas para administrador
                // Abrir a interface TabelaConta para administrar as contas cadastradas
                TabelaConta tabelaConta = new TabelaConta();
                tabelaConta.setVisible(true);
                dispose();  // Fechar a tela atual, se necessário
            } else {
                // Exiba mensagem de erro
                JOptionPane.showMessageDialog(null, "Frase mágica inválida para administrador", "Erro", JOptionPane.ERROR_MESSAGE);
                comboBox.setSelectedItem("Usuário"); // Volta para a opção "Usuário"
            }
        }
    
    }//GEN-LAST:event_tipoContaActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ano;
    private javax.swing.JTextField CPF;
    private javax.swing.JButton Cadastrar;
    private javax.swing.JTextField Dia;
    private javax.swing.JTextField Email;
    private javax.swing.JButton Limpar;
    private javax.swing.JTextField Mes;
    private javax.swing.JTextField Nome;
    private javax.swing.JPasswordField Senha;
    private javax.swing.JButton carregarFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JComboBox<String> tipoConta;
    // End of variables declaration//GEN-END:variables
}
