package CLASSESPESSOAA;

public class Funcionario extends Pessoa{
 
    //FUNCIONARIO IRA ABRIR A TELA DE TABELA DE LIVROS
    
    //PARA REALIZAR O ACESSO A FUNCIONARIOS EM CADASTRO A SENHA É "junindograu"
    
    //PARA FAZER O LOGIN E ABRIR A TELCA DE TABELA DE LIVROS TODOS QUE TIVEREM FUNCIONARIO
    //IRÁ ABRIR
    
    
}
